
name: jugoncalv.es
markdown: redcarpet
pygments: true

# permalink as /:category/:title
permalink: /blog/:categories/:title

# exclude my node related stuff
exclude: ['package.json', 'Makefile', 'src']
